matrix:
  os: linux
  dist: bionic
  arch: arm64-graviton2
  group: dev

  include:
#  - language: ruby
#    rvm:
#    - 2.5
#    script:
#    - ruby hello.rb
#
#  - language: cpp
#    compiler: clang
#    script:
#    - g++ hello.cpp
#
#  - language: python
#    script:
#    - python hello.py
#
#  - language: node_js
#    node_js:
#    - node
#    script:
#    - node hello.js
#
#  - language: java
#    jdk: openjdk8
#    script:
#    - mvn clean install

#   - language: go
#     script:
#     - go run ./hello.go
    
    

#  - language: php
#    php: '7.0'
#    script:
#    - php hello.php

  - language: perl
    perl: '5.30'
    before_install:
         - "nvm install node && nvm use node"
         - "npm install -g dredd"
         - cd ..
         - cd travis_test_p1_3/
         - "bundle install"
        
    script:
    - perl hello.PL

#  - language: csharp
#    script:
#    - csc hello.cs
#    - mono hello.exe

#   - language: smalltalk
#     os:
#       - linux
#     smalltalk_vm:
#     - Squeak-5.0
#     smalltalk:
#     - Squeak64-trunk
